/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        parchment:       '#F7F3ED',
        'surface-alt':   '#EDE8E0',
        ink:             '#111111',
        'ink-soft':      '#8A8278',
        'ink-muted':     '#B0A89C',
        'ink-ghost':     '#C8C0B4',
        'ink-dim':       '#D8D0C8',
        accent:          '#3D5AFE',
        'accent-soft':   '#8090EE',
        'accent-bg':     '#EEF0FF',
        'accent-border': '#C8D0FF',
        border:          '#E8E2DA',
        'border-soft':   '#E0D8CE',
        'border-task':   '#F0E8E0',
        dark:            '#111111',
        'dark-text':     '#F7F3ED',
        'dark-muted':    '#666666',
        'dark-subtle':   '#555555',
        'exam-red':      '#8B4B4B',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '20px',
        xxl: '28px',
        xxxl: '32px',
      },
      borderRadius: {
        sm: '6px',
        md: '9px',
        lg: '12px',
        xl: '14px',
        '2xl': '16px',
        pill: '20px',
        full: '9999px',
      },
      fontFamily: {
        'serif-black': ['Fraunces_900Black'],
        'serif-bold': ['Fraunces_700Bold'],
        'serif-light-italic': ['Fraunces_300Light_Italic'],
        'sans-light': ['DMSans_300Light'],
        'sans-regular': ['DMSans_400Regular'],
        'sans-medium': ['DMSans_500Medium'],
      },
    },
  },
  plugins: [],
};
